export const Data = [
  {
    id: "1",
    title: "Cara Melakukan Trend Analysis",
    yt: "https://youtu.be/hRwSdKZLSek?si=I2hO-ff2WRlFDqvu",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/01-Cara-Melakukan-Trend-Analysis",
    category: "trading",
  },
  {
    id: "2",
    title: "Cara Melakukan Area Analysis",
    yt: "https://youtu.be/3wB-hCEwwaQ?si=wi9e8bGh5IDumPyB",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/02-Cara-Melakukan-Area-Analysis",
    category: "trading",
  },
  {
    id: "3",
    title: "Cara Melakukan Pattern Analysis",
    yt: "https://youtu.be/MOM6jtZuOV8?si=PNlGz0ZvVjodjgkE",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/03-Cara-Melakukan-Pattern-Analysis",
    category: "trading",
  },
  {
    id: "4",
    title: "Cara Melakukan Trigger Analysis",
    yt: "https://youtu.be/OqemBcPFU-o?si=ZvJoiHxNfPyYSzry",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/04-Cara-Melakukan-Trigger-Analysis",
    category: "trading",
  },
  {
    id: "5",
    title: "Cara Melakukan Entry Exit Analysis",
    yt: "https://youtu.be/7azEMfMovVo?si=SogvtnGOmv38iO-A",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/05-Cara-Melakukan-Entry-Exit-Analysis",
    category: "trading",
  },
  {
    id: "6",
    title: "Intro to Fundamental Research",
    yt: "https://youtu.be/VBN97ZSvCOs?si=mF2ugRVN6KQdRHDE",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/06-Intro-to-Fundamental-Research",
    category: "trading",
  },
  {
    id: "7",
    title: "Faktor yang Berperan Dalam Fundamental Research",
    yt: "https://youtu.be/9IP8V3GF9-c?si=a-E7p7A3peD5CI4K",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/07-Faktor-yang-Berperan-Dalam-Fundamental-Research",
    category: "trading",
  },
  {
    id: "8",
    title: "Mendalami Tokenomics Project",
    yt: "https://youtu.be/sgi911A_AF0?si=mA7B8M-pbCQdgO2T",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/08-Mendalami-Tokenomics-Project",
    category: "trading",
  },
  {
    id: "9",
    title: "Intro To Narrative Analysis",
    yt: "https://youtu.be/NJKkPfEHoQU?si=ju2xY-2_i1NoTQYM",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/09-Intro-To-Narrative-Analysis",
    category: "trading",
  },
  {
    id: "10",
    title: "How to be Early in Every Narratives",
    yt: "https://youtu.be/YhsTxV_EhWk?si=4ElNv373DEbvhclH",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/10-How-to-be-Early-in-Every-Narratives",
    category: "trading",
  },
  {
    id: "11",
    title: "Portofolio Allocation",
    yt: "https://youtu.be/HCJ9WZw6lTs?si=aBDt9XZ5fkmJTUvC",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/11-Portofolio-Allocation",
    category: "trading",
  },
  {
    id: "12",
    title: "Possible Narratives For Next Bull Run",
    yt: "https://youtu.be/rVUJtwq73WM?si=U-5mTp09F_U6lfas",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/12-Possible-Narratives-For-Next-Bull-Run",
    category: "trading",
  },
  {
    id: "13",
    title: "Spatial Computing Narative",
    yt: "https://youtu.be/8w6Z1N41CFc?si=ewjUKGkTyj5vdV0E",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/13-Spatial-Computing-Narative",
    category: "trading",
  },
  {
    id: "14",
    title: "Pemahaman Dasar Altcoins",
    yt: "https://youtu.be/EhnKK1NNXVI?si=_WLuVZ37xm5TXaT7",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/14-Pemahaman-Dasar-Altcoins",
    category: "trading",
  },
  {
    id: "15",
    title: "Pemahaman Dasar Teknik Scalping",
    yt: "https://youtu.be/nhlzn9zc6F4?si=FYkdtl-7kIVP3dEt",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/15-Pemahaman-Dasar-Teknik-Scalping",
    category: "trading",
  },
  {
    id: "16",
    title: "Persiapan Mental Sebelum Scalping",
    yt: "https://youtu.be/gcfuCS_Y7g0?si=cZcptn-pXxXjhI7u",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/16-Persiapan-Mental-Sebelum-Scalping",
    category: "trading",
  },
  {
    id: "17",
    title: "Persiapan Teknikal Sebelum Scalping",
    yt: "https://youtu.be/EL5EZadLNX8?si=tx3iTEUl0q1sJR_8",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/17-Persiapan-Teknikal-Sebelum-Scalping",
    category: "trading",
  },
  {
    id: "18",
    title: "Cara Melakukan Screening Altcoins untuk Scalping",
    yt: "https://youtu.be/05Gxk1aQJsY?si=0JchDq5hNAs4ndgJ",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/18-Cara-Melakukan-Screening-Altcoins-untuk-Scalping",
    category: "trading",
  },
  {
    id: "19",
    title: "Pengenalan On Chain Trading",
    yt: "https://youtu.be/jYlQ1itkKVA?si=adNjel4-O1cRvtNB",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/19-Pengenalan-On-Chain-Trading",
    category: "trading",
  },
  {
    id: "20",
    title: "Menggali Decentralized Exchange",
    yt: "https://youtu.be/m9IrsnSB_KM?si=TVlNLz73Ye9SOz98",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/20-Menggali-Decentralized-Exchange",
    category: "trading",
  },
  {
    id: "21",
    title: "Cara Menggunakan Wallet dan Exchange",
    yt: "https://youtu.be/zvWpGEniJOo?si=ycaLpaNtNDVeui5L",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/21-Cara-Menggunakan-Wallet-dan-Exchange",
    category: "trading",
  },
  {
    id: "22",
    title: "Tools untuk On Chain",
    yt: "https://youtu.be/DepwwKOVEDM?si=mZ4SxA6d0ke8mAwz",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/22-Tools-untuk-On-Chain",
    category: "trading",
  },
  {
    id: "23",
    title: "Kesalahan yang harus dihindari Sebelum Transaksi On Chain",
    yt: "https://youtu.be/lwK4ljr2DeU?si=-tUByCOnYe70ugHe",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/23-Kesalahan-yang-harus-dihindari-Sebelum-Transaksi-On-Chain",
    category: "trading",
  },
  {
    id: "24",
    title: "Pengenalan Dow Theory",
    yt: "https://youtu.be/WOhc-iqF_d0?si=cm7JsUgWaQIfq9wM",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/24-Pengenalan-Dow-Theory",
    category: "trading",
  },
  {
    id: "25",
    title: "Memahami Konsep Trend dalam Dow Theory",
    yt: "https://youtu.be/V97YgNia5RM?si=0Syjl-lYxDyDjaFZ",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/25-Memahami-Konsep-Trend-dalam-Dow-Theory",
    category: "trading",
  },
  {
    id: "26",
    title: "Memahami Konsep Trend Lanjutan Dalam Dow Theory",
    yt: "https://youtu.be/yqoD4XuM9ZU?si=SsEHHug_ajPMFSyS",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/26-Memahami-Konsep-Trend-Lanjutan-Dalam-Dow-Theory",
    category: "trading",
  },
  {
    id: "27",
    title: "Penggunaan Moving Averages dan Validasi Dow",
    yt: "https://youtu.be/cKNC3-Fvk64?si=VqdR7sqUq5zMSFpX",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/27-Penggunaan-Moving-Averages-dan-Validasi-Dow",
    category: "trading",
  },
  {
    id: "28",
    title: "Fase pada Dow Theory",
    yt: "https://youtu.be/6WleD8_o4sk?si=z5VIUQKp2VATpSGe",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/28-Fase-pada-Dow-Theory",
    category: "trading",
  }
];