export const Data = [
  {
    id: "1",
    title: "Apa itu Smart Money",
    yt: "https://youtu.be/rPMnGzmOSDE?si=niGk9vQk_NCCGMyX",
    link: "/Halaman/page/1-crypto-trading/05-Crypto-Smart-Money-Kalimasada/01-Apa-itu-Smart-Money",
    category: "crypto",
  },
  {
    id: "2",
    title: "Apa Fokus dari Smart Money",
    yt: "https://youtu.be/YT9lICVb6eg?si=bah_Ilj6X8Fo14DH",
    link: "/Halaman/page/1-crypto-trading/05-Crypto-Smart-Money-Kalimasada/02-Apa-Fokus-dari-Smart-Money",
    category: "crypto",
  },
  {
    id: "3",
    title: "Konsep Liquidity 1",
    yt: "https://youtu.be/13FBLIubfOw?si=jcSL_3HruMWTZ3wk",
    link: "/Halaman/page/1-crypto-trading/05-Crypto-Smart-Money-Kalimasada/03-Konsep-Liquidity-1",
    category: "crypto",
  },
  {
    id: "4",
    title: "Konsep Liquidity 2",
    yt: "https://youtu.be/obzt4DcP5Zw?si=S95wZgKQ_49LzBKV",
    link: "/Halaman/page/1-crypto-trading/05-Crypto-Smart-Money-Kalimasada/04-Konsep-Liquidity-2",
    category: "crypto",
  },
  {
    id: "5",
    title: "Konsep Liquidity 3",
    yt: "https://youtu.be/_quSKtfecjM?si=guAZEwW9MwLbfFCV",
    link: "/Halaman/page/1-crypto-trading/05-Crypto-Smart-Money-Kalimasada/05-Konsep-Liquidity-3",
    category: "crypto",
  },
  {
    id: "6",
    title: "Market Structure",
    yt: "https://youtu.be/CqlzfPXHu6k?si=1CgB86p8ICUVPP32",
    link: "/Halaman/page/1-crypto-trading/05-Crypto-Smart-Money-Kalimasada/06-Market-Structure",
    category: "crypto",
  },
  {
    id: "7",
    title: "Change of Character",
    yt: "https://youtu.be/NgOEDta-mko?si=TJlzxOmq_3BVihXG",
    link: "/Halaman/page/1-crypto-trading/05-Crypto-Smart-Money-Kalimasada/07-Change-of-Character",
    category: "crypto",
  },
  {
    id: "8",
    title: "Orderblock",
    yt: "https://youtu.be/JTDskg8gaek?si=LwIrTLiVbHS5oorr",
    link: "/Halaman/page/1-crypto-trading/05-Crypto-Smart-Money-Kalimasada/08-Orderblock",
    category: "crypto",
  },
  {
    id: "9",
    title: "Momentum",
    yt: "https://youtu.be/KB_l7P2_JkQ?si=_FeWXPkzlBrV5MnN",
    link: "/Halaman/page/1-crypto-trading/05-Crypto-Smart-Money-Kalimasada/09-Momentum",
    category: "crypto",
  },
  {
    id: "10",
    title: "Penerapan Smart Money",
    yt: "https://youtu.be/jPhR_xH_2JE?si=HE_5dVNv5vvDhSdF",
    link: "/Halaman/page/1-crypto-trading/05-Crypto-Smart-Money-Kalimasada/10-Penerapan-Smart-Money",
    category: "crypto",
  }
];